// Font Awesome configuration
import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faPlus, 
  faMinus, 
  faCheck, 
  faTimes, 
  faEdit, 
  faTrash, 
  faSave, 
  faHome, 
  faTasks, 
  faRobot, 
  faComments, 
  faUser, 
  faEnvelope, 
  faPhone, 
  faSearch, 
  faFilter, 
  faStar, 
  faStarHalfAlt,
  faEye,
  faEyeSlash,
  faSpinner,
  faExclamationTriangle,
  faInfoCircle,
  faCheckCircle,
  faTimesCircle,
  faBars,
  faChevronDown,
  faChevronUp,
  faArrowLeft,
  faArrowRight,
  faRefresh,
  faCog,
  faCalendar,
  faClock,
  faChartBar,
  faDatabase,
  faCloudUploadAlt,
  faDownload,
  faUpload,
  faLink,
  faExternalLinkAlt,
  faPaperclip,
  faTag,
  faLanguage,
  faBell,
  faHeart,
  faThumbsUp,
  faShareAlt,
  faFlag,
  faBookmark,
  faLightbulb,
  faQuestionCircle,
  faSync,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faAngleDown
} from '@fortawesome/free-solid-svg-icons';

import { 
  faStar as farStar,
  faHeart as farHeart,
  faBookmark as farBookmark,
  faEye as farEye,
  faUser as farUser,
  faComment as farComment
} from '@fortawesome/free-regular-svg-icons';

import {
  faGithub,
  faLinkedin,
  faTwitter,
  faFacebook,
  faGoogle,
  faReact,
  faNodeJs,
  faDocker
} from '@fortawesome/free-brands-svg-icons';

// Add icons to the library
library.add(
  // Solid icons
  faPlus, 
  faMinus, 
  faCheck, 
  faTimes, 
  faEdit, 
  faTrash, 
  faSave, 
  faHome, 
  faTasks, 
  faRobot, 
  faComments, 
  faUser, 
  faEnvelope, 
  faPhone, 
  faSearch, 
  faFilter, 
  faStar, 
  faStarHalfAlt,
  faEye,
  faEyeSlash,
  faSpinner,
  faExclamationTriangle,
  faInfoCircle,
  faCheckCircle,
  faTimesCircle,
  faBars,
  faChevronDown,
  faChevronUp,
  faArrowLeft,
  faArrowRight,
  faRefresh,
  faCog,
  faCalendar,
  faClock,
  faChartBar,
  faDatabase,
  faCloudUploadAlt,
  faDownload,
  faUpload,
  faLink,
  faExternalLinkAlt,
  faPaperclip,
  faTag,
  faLanguage,
  faBell,
  faHeart,
  faThumbsUp,
  faShareAlt,
  faFlag,
  faBookmark,
  faLightbulb,
  faQuestionCircle,
  faSync,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faAngleDown,
  
  // Regular icons
  farStar,
  farHeart,
  farBookmark,
  farEye,
  farUser,
  farComment,
  
  // Brand icons
  faGithub,
  faLinkedin,
  faTwitter,
  faFacebook,
  faGoogle,
  faReact,
  faNodeJs,
  faDocker
);